services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    volumes:
      - /etc/prometheus:/etc/prometheus:ro
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - grafana

volumes:
  prom_data: {}
  grafana_data: {}

networks:
  grafana:
    driver: bridge
