services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/${PG_DB}
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASS}
      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start --hostname https://auth.asleepdev.xyz --proxy-headers forwarded --http-enabled true
    depends_on:
      - keycloakdb
    networks:
      - keycloak
    ports:
      - 8080:8080

  keycloakdb:
    image: postgres:latest
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    networks:
      - keycloak

volumes:
  keycloak_data:

networks:
  keycloak:
    driver: bridge
