services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
      - "8888:8888/tcp"
    volumes:
      - 'satisfactory_data:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
      - MULTIHOME=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 8G
  # only needed for mods
  sftp-server:
    container_name: 'sftp-server'
    image: 'atmoz/sftp:latest'
    volumes:
      - 'satisfactory_data:/home/${SFTP_USER}/satisfactory-server'
    ports:
      - '2222:22'
    # set the user and password, and the user's UID (this should match the PUID and PGID of the satisfactory-server container)
    command: '${SFTP_USER}:${SFTP_PASS}:1000'

volumes:
  satisfactory_data: {}
