services:
  vaultwarden:
    image: vaultwarden/server:1.34.1
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    volumes:
      - vaultwarden:/data
    ports:
      - "80:80"

volumes:
  vaultwarden: {}
