services:
  vaultwarden:
    image: vaultwarden/server:1.34.1
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - vaultwarden:/data
    ports:
      - 3000:3000

volumes:
  vaultwarden: {}
